version: '3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3333:3333"
    volumes:
      - .:/usr/src/app
    environment:
      - NODE_ENV=development
